### ISSUE TITLE
[afreecatv] Only part of the video will be downloaded.

### ISSUE THREAD

**Issue by jooburn** [ytdl-patched/ytdl-patched#44] opened 2022-08-01 14:41 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

South Korea

### Provide a description that is worded well enough to be understood

hello
Only part of the video will be downloaded.
It will only be downloaded until you set an age limit.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -o "/video/%(title)s.mp4" -vU --cookies /video/cookies.txt -- https://vod.afreecatv.com/ST/89035788
[debug] Command-line config: ['-o', '/video/%(title)s.mp4', '-vU', '--cookies', '/video/cookies.txt', '--', 'https://vod.afreecatv.com/ST/89035788']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.07.18 [135f05ef6]
[debug] Lazy loading extractors is disabled
[debug] Python 3.8.5 (CPython 64bit) - Linux-4.4.180+-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://vod.afreecatv.com/ST/89035788
[generic] 89035788: Downloading webpage
[redirect] Following redirect to https://vod.afreecatv.com/player/89035788
[debug] [afreecatv] Extracting URL: https://vod.afreecatv.com/player/89035788
[afreecatv] 89035788: Downloading webpage
[afreecatv] 89035788: Downloading video info XML
WARNING: [afreecatv] In accordance with local laws and regulations, underage users are restricted from watching adult content. Only content suitable for all ages will be downloaded. Provide account credentials if you wish to download restricted content.
[afreecatv] 89035788: Downloading video info XML (skipping adult)
[afreecatv] 89035788: Downloading part 1 m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[afreecatv] 89035788: Downloading part 2 m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Downloading multi_video: 신입 여캠 술방 (쌩얼 이해바람)
[afreecatv] Playlist 신입 여캠 술방 (쌩얼 이해바람): Downloading 2 videos of 2
[debug] The information of all playlist entries will be held in memory
[download] Downloading video 1 of 2
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 20220627_E1B4B8A8_241344973_1: Downloading 1 format(s): hls-original
[debug] Invoking hlsnative downloader on "http://vod-archive-kr-cdn-z01.afreecatv.com/v101/hls/vod/20220627/973/241344973/REGL_E1B4B8A8_241344973_1.smil/original/both/playlist.m3u8"
[download] /video/신입 여캠 술방 (쌩얼 이해바람) (part 1).mp4 has already been downloaded
[download] 100% of 39.79MiB
[download] Downloading video 2 of 2
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 89035788_2: Downloading 1 format(s): hls-original
[debug] Invoking hlsnative downloader on "http://vod-archive-kr-cdn-z01.afreecatv.com/v101/hls/vod/info/HIDE.mp4/original/both/playlist.m3u8"
[download] /video/신입 여캠 술방 (쌩얼 이해바람) (part 2).mp4 has already been downloaded
[download] 100% of 18.51KiB
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:/video/신입 여캠 술방 (쌩얼 이해바람) (part 1).mp4'
[debug] Codecs = aac, h264
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:/video/신입 여캠 술방 (쌩얼 이해바람) (part 2).mp4'
[debug] Codecs = h264
ERROR: The files have different streams/codecs and cannot be concatenated. Either select different formats or --recode-video them to a common format
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1437, in wrapper
return func(self, *args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1534, in __extract_info
return self.process_ie_result(ie_result, download, extra_info)
File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1661, in process_ie_result
return self.__process_playlist(ie_result, download)
File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1819, in __process_playlist
ie_result = self.run_all_pps('playlist', ie_result)
File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3409, in run_all_pps
info = self.run_pp(pp, info)
File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3388, in run_pp
files_to_delete, infodict = pp.run(infodict)
File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/common.py", line 25, in run
ret = func(self, info, *args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/common.py", line 126, in wrapper
return func(self, info)
File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 1164, in run
files_to_delete = self.concat_files(in_files, out_file)
File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 1139, in concat_files
raise PostProcessingError(
yt_dlp.utils.PostProcessingError: The files have different streams/codecs and cannot be concatenated. Either select different formats or --recode-video them to a common format
```

**Comment by Lesmiscore** [comment] 2022-08-01 14:54
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/4526

**Closed as not planned by Lesmiscore** 2022-08-01 14:54 UTC
