### ISSUE TITLE
Iwara.tv: Inform if Private videos

### ISSUE THREAD

**Issue by afterdelight** [ytdl-patched/ytdl-patched#36] opened 2022-05-30 01:35 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Instead of an error message, inform user if its a private video and cant be downloaded.

### Verbose log

```shell
F:\downloader\iwara.tv\dl>ytdl-patched https://ecchi.iwara.tv/videos/e8qgbhwwxhmxyq39 --conf config_iwara --verbose
[debug] Command-line config: ['https://ecchi.iwara.tv/videos/e8qgbhwwxhmxyq39', '--conf', 'config_iwara', '--verbose']
[debug] | Config "config_iwara": ['--continue', '--http-chunk-size', '1M', '--buffer-size', '16K', '--sub-lang', 'english', '--embed-metadata', '--embed-thumbnail', '--abort-on-unavailable-fragment', '-o', '%(age_limit)s\\%(uploader)s\\%(title)s [%(id)s].%(ext)s', '--download-archive', 'downloaded.txt', '-f', 'Source/540p/360p', '--ffmpeg-location', 'D:\\Program Files\\ffmpeg\\bin']
[debug] User config "C:\Users\X\AppData\Roaming\yt-dlp\config": ['--continue', '--format-sort', 'vbr,abr', '--http-chunk-size', '1M', '--buffer-size', '16K', '--sub-lang', 'english', '--embed-metadata', '--abort-on-unavailable-fragment', '-o', '%(title)s [%(id)s].%(ext)s', '--ffmpeg-location', 'D:\\Program Files\\ffmpeg\\bin']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] ytdl-patched version 2022.05.18
[debug] ** The command you are running is not yt-dlp.
[debug] ** Please make bug reports at https://github.com/ytdl-patched/ytdl-patched/issues/new/choose instead.
[debug] Lazy loading extractors is disabled
[debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: "D:\Program Files\ffmpeg\bin\ffmpeg" -bsfs
[debug] Checking exe version: "D:\Program Files\ffmpeg\bin\ffprobe" -bsfs
[debug] exe versions: ffmpeg 2022-03-28-git-5ee198f9aa-essentials_build-www.gyan.dev (setts), ffprobe 2022-03-28-git-5ee198f9aa-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, WebSocketsWrapper-None, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] Loading archive file 'downloaded.txt'
[debug] [iwara] Extracting URL: https://ecchi.iwara.tv/videos/e8qgbhwwxhmxyq39
[iwara] e8qgbhwwxhmxyq39: Downloading webpage
[iwara] [debug] Fetching webpage from https://ecchi.iwara.tv/videos/e8qgbhwwxhmxyq39
[iwara] e8qgbhwwxhmxyq39: Downloading JSON metadata
[iwara] [debug] Fetching webpage from http://www.iwara.tv/api/video/e8qgbhwwxhmxyq39
ERROR: [iwara] e8qgbhwwxhmxyq39: Unable to extract iframe URL; please report this issue on  https://github.com/ytdl-patched/ytdl-patched/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "C:\Python\Python310\lib\site-packages\yt_dlp\extractor\iwara.py", line 79, in _real_extract
    iframe_url = self._html_search_regex(
  File "C:\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 1299, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "C:\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 1290, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by Lesmiscore** [comment] 2022-05-31 01:51
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/3852

**Closed as not planned by Lesmiscore** 2022-05-31 01:51 UTC
